== Introduction

This lecture note presents the JSX/TSX extension syntax to the JavaScript and TypeScript languages.

== The JSX extension syntax

In the link:https://react.dev/[React] library, the definition of user interfaces is done by creating a tree of elements and text nodes.
This is achieved via the `React.createElement` function, which has the following parameters:

* The HTML element name or a reference to a React component.
* An object with the element attributes.
* A variable argument list containing the element's children.

The following code illustrates the use of this function to create a div containing a paragraph and an unordered list with two items.

[#createElement-example, typescript]
----
import React from "react"
const tree: React.ReactElement = React.createElement("div", { id: "div-id" },
    React.createElement("p", null, "List of Items:"),
    React.createElement("ul", null,
        React.createElement("li", null, "Item 0"),
        React.createElement("li", null, "Item 1")
    )
);
----

Note how the tree of elements and text nodes is created by a single JavaScript composite expression (and not a set of statements).

JSX is a syntactical extension to the JavaScript language (TSX for the TypeScript) allowing the use of an HTML-like syntax to define these trees of elements.
The following JSX expression is fully equivalent to the previous TypeScript expression.
[#tsx-example-1, typescript]
----
import React from "react"
const tree: React.ReactElement = 
    <div id="div-id">
        <p>List of Items:</p>
        <ul>
            <li>Item 0</li>
            <li>Item 1</li>
        </ul>
    </div>
----

The browser's JavaScript execution environment does not support the JSX syntax extension.
This means that JSX expressions need to be converted into their pure JavaScript equivalents, during the build process and before the program is provided to the browser.
This is similar to the static type erasure process applied to TypeScript programs during the build process.
In fact, the TypeScript compiler can do both in a single pass: remove the static type information and translate JSX expressions into the equivalent JavaScript expressions.

It is important to highlight that:

* A JSX expression does _not_ in any way interact with the browser's DOM. It is a side-effect free expression that evaluates to a React element.
* It is an expression, meaning that it can be used anywhere an expression can be used.

The following code illustrates the use of JSX expressions in different places.

[#tsx-example-2, typescript]
----
import React from "react"
// As elements of a literal array
const elements = [
    <p>Hello</p>,
    <p>World</p>
]

// As arguments to functions
function doSomethingWithElements(elem: React.ReactElement) { /*...*/ }
doSomethingWithElements(<p>used in an argument</p>)

// As object property values
const anObject = {
    aParagraph: <p>Hello</p>,
    anInput: <input type="text" />,
}
----

TIP: Go to the link:https://www.typescriptlang.org/play[TypeScript Playground], paste the above code and see the resulting pure JavaScript code in the right pane.

JSX expressions allow TypeScript expressions inside them.
Consider the following code excerpt

[#tsx-example-3, typescript]
----
import React from "react"
const expr0 = <p>1+2</p>
const expr1 = <p>{1+2}</p>
----

The translation to pure JavaScript results in the following code.

[#tsx-example-3-translated, typescript]
----
import React from "react";
const expr0 = React.createElement("p", null, "1+2");
const expr1 = React.createElement("p", null, 1 + 2);
----

Note how on `expr0`, the `1+2` inside the `p` element is interpreted as a _literal string_ and used that way for the third argument of the `createElement` call.
In contrast, for `expr1`, the `1+2` is interpreted as a JavaScript expression and provided that way to the `createElement` function.

That is, it is possible to include a JavaScript expression inside a JSX expression, by surrounding it with curly braces ('{' and '}').

The following example is slightly more complex.

[#tsx-example-4, typescript]
----
import React from "react"
const names = ['alice', 'bob']
const element: React.ReactElement = 
    <div>
        {names.map(name => <p>{name}</p>)}
    </div>
----

The translated pure JavaScript is the following.
[#tsx-example-4-translated, typescript]
----
import React from "react";
const names = ['alice', 'bob'];
const element = React.createElement("div", null, 
    names.map(name => React.createElement("p", null, name))
);
----

Note how:

* the JSX expression contains an inner JavaScript expression (the `names.map(...)` expression);
* the inner JavaScript expression has itself an inner JSX expression (the `<p>...</p>` expression).

A JSX expression can have an inner JavaScript _expression_ but not a _statement_.
That's why, in the previous example, we needed to use a _functional_ map instead of a more _imperative_ for-loop.

NOTE: When using more recent React versions, the recommended translation from JSX is into a `jsx` function and not into the `createElement` function. In this lecture note we used the _classic_ translation because we consider it to be easier to understand.

== Exercises

Solve the following exercises, using the link:https://www.typescriptlang.org/play[TypeScript Playground] to observe the translated pure JavaScript.

* Using the JSX syntax, create a function that receives a string array and returns a React element representing an _unordered list_ (`ul` element),
where each list item (`li` element) holds the corresponding string from the array. Each of these strings should be surrounded by a `span` element with the `class` attribute set to `'item'`.

* Without using the JSX syntax, implement the previous function.

* Write the pure JavaScript expression equivalent to the following JSX expression:

[#tsx-exercise-3, typescript]
----
const elem: React.ReactElement = 
    <div
        id={"id1".toUpperCase()}
        data-a="1+2"
        data-b={1+2}
        data-c={<p>some text</p>}
    >
        {['x', 'y'].map(it => <p key={it}>it</p>)}
    </div>
----